### ISSUE TITLE
[ServerSide] Got error while call RequestDeviceAsync: Must be handling a user gesture to show a permission request

### ISSUE THREAD

**Issue by rsulab** [EngstromJimmy/Blazm.Bluetooth#1]

**Comment by rsulab** [comment]
![image](https://user-images.githubusercontent.com/58805372/92142888-2c205480-ee1d-11ea-89ad-97adc313762e.png)

**Comment by rsulab** [comment]
![image](https://user-images.githubusercontent.com/58805372/92144249-1d3aa180-ee1f-11ea-8f0d-0b1b024194cd.png)

**Comment by EngstromJimmy** [comment]
Is this the sample project you are running or something else?
What browser are you using?

To be able to execute requestDevice you need to execute it by pressing a button (you can't just start it without a user interaction).
That's a limitation in the specs.

**Comment by rsulab** [comment]
> Is this the sample project you are running or something else?

No, it was not sample project.

> What browser are you using?

Chrome last version(Opera and Edge gives same error)

> 
> To be able to execute requestDevice you need to execute it by pressing a button (you can't just start it without a user interaction).
> That's a limitation in the specs.

Well, need I call RequestDeviceAsync in button handler?

**Comment by EngstromJimmy** [comment]
Yes exactly, you need to run it in the Button handler, it's a limitation in the Web Bluetooth API.

**Comment by rsulab** [comment]
Ok

**Comment by jeffersyuan1976** [comment]
I am facing the same error, however, there is a little different.
I was running in maui&blazor project, it works fine in windows side, but it does not works in android side.
Any ides on it?
Thanks.
