### ISSUE TITLE
Can this library be used to print to Bluetooth Printer and BlueTooth QrCode Scanner ?

### ISSUE THREAD

**Issue by nssidhu** [EngstromJimmy/Blazm.Bluetooth#19]
Wondering if this library can be used to Print to Bluetooth thermal Printer for Receipt Printing with QrCode.
Similarly if this can be used to scan QrCode From Bluetooth connected QrCode Scanner.

**Comment by EngstromJimmy** [comment]
There is nothing built in specifically for this, if it is Bluetooth LE (Low Energy) I don't see why it wouldn't be possible.
If it is Bluetooth without the LE, it's not possible.

This library is using Web Bluetooth that only supports Low Energy at this point.
There is another API called Web Serial that might be usable for you.
However I have not looked at it at all, I do have some devices that would be fun to play with so I might implement that as well at some point but probably in another library.

https://caniuse.com/?search=web%20serial
