### ISSUE TITLE
Can only read first byte of array

### ISSUE THREAD

**Issue by Bengkel** [EngstromJimmy/Blazm.Bluetooth#26]
I created a Blazor app that communicates with an Arduino using Ble. I can write data to the device and also read data from the device. But when using the _ReadValueAsync_ I only receive the first byte of the array.

You can see the code [on Github](https://github.com/Bengkel/Bengkel.Ble). I also included a recording to demonstrate.

What am I doing wrong here?

**Comment by EngstromJimmy** [comment]
Maybe the device only gives you one byte?
You could test adding som debug code in the JavaScript file (if you download it from GitHub) to see what the browser API returns.

**Comment by Bengkel** [comment]
Good point, tested it with edge://bluetooth-internals and its seems to be by design.
