### ISSUE TITLE
compatibility for chrome ?

### ISSUE THREAD

**Issue by GregoryAmis** [EngstromJimmy/Blazm.Bluetooth#6]
Hello Jimmy, very interesting...
is Blazm.Bluetooth compatible for chrome on android phone ?

**Comment by EngstromJimmy** [comment]
According to this page https://community.estimote.com/hc/en-us/articles/360020420172-Which-browsers-support-Web-Bluetooth
it should work (I don't have a device to test on).
Blazm is using WebBluetooth in the background so it should work just fine =)
